/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/donations/sandbox/orders/{orderId}/reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the owner's Sandbox order query checkpoint */
        get: operations["getSandboxReconciliation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/donations/sandbox/orders/{orderId}/reconciliation/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Audit and queue another read-only query for the owner's original order
         * @description Only review caused by exhausted provider_unavailable retries within the 30-day query window may be requeued. The expected version prevents stale or duplicate requests. Other review causes, bill jobs and other users' orders remain inaccessible. Never creates an order or changes payment facts. The reset and user audit event commit atomically. Same-origin browser protections and verified bearer identity are required.
         */
        post: operations["retrySandboxReconciliation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Process liveness, including disabled mode */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Enabled runtime with reachable database
         * @description Startup verifies migration checksums without applying migrations. This probe checks database reachability within two seconds; it makes no bank calls and does not certify provider entitlement or end-to-end acceptance. Disabled mode returns 503. Never publish these probes through the gateway.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/donations/sandbox/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create or recover the actor's single-card Sandbox intent
         * @description Gateway strips forged identity headers. Service requires the exact Dapr gateway caller and trusted actor plus Sandbox test scope. Mutations use the canonical authenticated browser transport and CSRF policy. Persist one provider OrderNo before sending; ambiguous creation returns pending and must never silently create a new order. This operation accepts no card fields, actor, environment, bank URLs or recurring parameters.
         */
        post: operations["createSandboxCheckout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/donations/sandbox/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query the actor's own Sandbox order and verified facts */
        get: operations["getSandboxOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/donations/sandbox/returns/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve a short-lived return reference after login
         * @description Requires the same verified gateway identity and Sandbox test permission as own-order queries. A reference does not grant ownership. Until its callback has been verified, return only pending, with no financial detail. Completed work resolves only for the order owner. Missing, expired, review-state and cross-owner references return not_found. No bank query runs in this endpoint. References expire after 15 minutes; recover through the original owned order after expiry. All responses are private/no-store.
         */
        get: operations["resolveSandboxReturn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/donations/provider-webhooks/funbiz/sandbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Persist minimal Sandbox callback work before acknowledgement
         * @description Requires the exact configured Dapr gateway caller, but no donor JWT. JSON body limited to 4096 bytes. ShopNo must match fixed Sandbox config. V2.5 documents no notification signature. PayToken is only a hint: query OrderPayQuery via its authenticated encrypted protocol and match local environment, merchant, order, amount and payment type before crediting. Outer API Status is not payment success. No raw payload logging.
         */
        post: operations["receiveSandboxCallback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/donations/provider-return/funbiz/sandbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept form return without donor cookies and redirect safely
         * @description Requires the exact configured Dapr gateway caller, without donor cookies or JWT. Form body is limited to 4096 bytes; query parameters are ignored. Only one ShopNo and PayToken are accepted. Persist callback work and a hashed random 15-minute reference atomically before redirecting to the fixed Admin result page with ?ref=. Invalid form input redirects to the same page without a reference; storage failure is 503. No login/session is granted and PayToken never enters the redirect. Result details require login and order ownership. Return is not financial truth; the original owned order remains the recovery path. Runtime must rate-limit ingress and purge expired references before operational enablement.
         */
        post: operations["returnSandboxCheckout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RequeryStatus: {
            /** @enum {string} */
            state: "pending" | "processing" | "done" | "review";
            /** @enum {string} */
            reason: "" | "provider_unavailable" | "invalid_response" | "identity_conflict" | "unresolved_order" | "refund_review" | "unsupported_payment" | "outside_query_window" | "provider_review";
            retry_version: number;
            can_retry: boolean;
        };
        CheckoutInput: {
            /**
             * Format: int64
             * @description TWD minor units; 10000 represents TWD 100. Production finance limits are not yet approved.
             */
            amount_minor: number;
        };
        Notification: {
            ShopNo: string;
            PayToken: string;
        };
        Order: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            environment: "sandbox";
            /** Format: int64 */
            amount_minor: number;
            /** @enum {string} */
            currency: "TWD";
            /** @enum {string} */
            creation_state: "reserved" | "create_unknown" | "checkout_ready" | "create_failed";
            /**
             * Format: uri
             * @description Bank-hosted HTTPS URL on an exact allowlisted Sandbox origin; owner-only, never logged
             */
            checkout_url?: string;
            outcomes: {
                /** @enum {string} */
                kind: "authorization" | "capture" | "settlement";
                success: boolean;
                provider_date: string;
            }[];
        };
        Error: {
            /** @enum {string} */
            code: "invalid_input" | "unauthorized" | "forbidden" | "not_found" | "idempotency_conflict" | "provider_unavailable";
        };
    };
    responses: {
        /** @description Invalid/unknown input or environment/card override */
        Invalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description HHC login required */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing exact Sandbox permission or untrusted service caller */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Idempotency payload mismatch, stale retry version or query not eligible for retry */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Provider/configuration unavailable; no automatic fallback or blind create retry */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Environment/actor-scoped printable key; changed payload returns conflict */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSandboxReconciliation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owner-only query state; no provider identity or payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequeryStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description No owned order checkpoint exists */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    retrySandboxReconciliation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    expected_retry_version: number;
                };
            };
        };
        responses: {
            /** @description Original-order query queued; this is not payment confirmation */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "queued";
                    };
                };
            };
            400: components["responses"]["Invalid"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Order does not belong to the authenticated user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is listening; not bank or payment readiness */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enabled runtime and database reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Disabled runtime or database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createSandboxCheckout: {
        parameters: {
            query?: never;
            header: {
                /** @description Environment/actor-scoped printable key; changed payload returns conflict */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutInput"];
            };
        };
        responses: {
            /** @description Existing or newly prepared bank-hosted checkout */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description Creation remains uncertain; query the same order */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["Invalid"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    getSandboxOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Own Sandbox order; includes no card fragments or charge tokens */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Missing or not owned in this environment */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    resolveSandboxReturn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verified reference resolves to an owned Sandbox order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description Callback verification is pending; no financial details */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        state: "pending";
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Missing, expired, unresolved review or not owned */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    receiveSandboxCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Notification"];
            };
        };
        responses: {
            /** @description Work durably stored, not payment acceptance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        Status: "S";
                    };
                };
            };
            400: components["responses"]["Invalid"];
            403: components["responses"]["Forbidden"];
            503: components["responses"]["Unavailable"];
        };
    };
    returnSandboxCheckout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Notification"];
            };
        };
        responses: {
            /** @description Fixed Admin result destination; opaque reference or generic error */
            303: {
                headers: {
                    /** @description Fixed https://admin.alive.org.tw/donations/sandbox/result destination */
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            503: components["responses"]["Unavailable"];
        };
    };
}
