/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCampaigns"];
        put?: never;
        post: operations["createCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/campaigns/{campaignId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: string;
            };
            cookie?: never;
        };
        get: operations["getCampaign"];
        put: operations["updateCampaign"];
        post?: never;
        delete: operations["deleteCampaign"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/campaigns/{campaignId}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/campaigns/{campaignId}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCampaignDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/campaigns/{campaignId}/retry-failed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retryFailedCampaignDeliveries"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/campaign-schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCampaignSchedules"];
        put?: never;
        post: operations["createCampaignSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/campaign-schedules/{scheduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: string;
            };
            cookie?: never;
        };
        get: operations["getCampaignSchedule"];
        put: operations["updateCampaignSchedule"];
        post?: never;
        delete: operations["deleteCampaignSchedule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bulletins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPublicBulletins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bulletins/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLatestPublicBulletin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bulletins/by-number/{issueNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicBulletinByNumber"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bulletins/{issueDate}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicBulletinByDate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPublicNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPublicHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPublicVideos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicHome"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bulletins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminBulletins"];
        put?: never;
        post: operations["createBulletinIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bulletins/{issueId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminBulletin"];
        put: operations["updateBulletinIssue"];
        post?: never;
        delete: operations["deleteBulletin"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bulletins/{issueId}/upload-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createBulletinUploadSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bulletins/{issueId}/versions/{locale}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateBulletinVersion"];
        post?: never;
        delete: operations["deleteBulletinVersion"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bulletins/{issueId}/assets/{assetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBulletinAssetStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bulletins/{issueId}/assets/{assetId}/scan/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retryBulletinAssetScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bulletins/{issueId}/assets/{assetId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeBulletinUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bulletins/{issueId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publishBulletin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bulletins/{issueId}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unpublishBulletin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bulletins/{issueId}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBulletinRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bulletins/{issueId}/revisions/{revision}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restoreBulletinRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/content/{module}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminContent"];
        put?: never;
        post: operations["createContent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/content/{module}/{contentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminContent"];
        put: operations["updateContent"];
        post?: never;
        delete: operations["deleteContent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/content/{module}/{contentId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publishContent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/content/{module}/{contentId}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unpublishContent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/content/{module}/{contentId}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listContentRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/content/{module}/{contentId}/revisions/{revision}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restoreContentRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/content/news/{contentId}/upload-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createNewsCoverUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/content/news/{contentId}/assets/{assetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNewsCoverStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/content/news/{contentId}/assets/{assetId}/scan/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retryNewsCoverScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/content/news/{contentId}/assets/{assetId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeNewsCoverUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CampaignTranslation: {
            subject: string;
            body: string;
            /**
             * @description Web push click behavior. URL requires actionUrl; home and dismiss omit it.
             * @enum {string}
             */
            clickBehavior?: "home" | "url" | "dismiss";
            actionUrl?: string;
        };
        CreateCampaign: {
            name: string;
            /** @enum {string} */
            channel: "email" | "web_push";
            /** @enum {string} */
            audienceType: "newsletter" | "all" | "role" | "users";
            /** Format: uuid */
            roleId?: string;
            userIds?: string[];
            translations: {
                [key: string]: components["schemas"]["CampaignTranslation"];
            };
        };
        UpdateCampaign: {
            name: string;
            /** @enum {string} */
            channel: "email" | "web_push";
            /** @enum {string} */
            audienceType: "newsletter" | "all" | "role" | "users";
            /** Format: uuid */
            roleId?: string;
            userIds?: string[];
            translations: {
                [key: string]: components["schemas"]["CampaignTranslation"];
            };
        };
        CreateCampaignSchedule: {
            name: string;
            /** @enum {string} */
            channel: "email" | "web_push";
            /** @enum {string} */
            audienceType: "newsletter" | "all" | "role" | "users";
            /** Format: uuid */
            roleId?: string;
            userIds?: string[];
            /** @enum {string} */
            scheduleType: "once" | "cron";
            /** Format: date-time */
            runAt?: string | null;
            cronExpression?: string;
            /** @default Asia/Taipei */
            timezone: string;
            translations: {
                [key: string]: components["schemas"]["CampaignTranslation"];
            };
        };
        UpdateCampaignSchedule: components["schemas"]["CreateCampaignSchedule"] & {
            enabled: boolean;
        };
        /**
         * @default zh-Hant
         * @enum {string}
         */
        Locale: "zh-Hant" | "zh-Hans" | "en" | "ja" | "ko";
        /** @enum {string} */
        BulletinStatus: "draft" | "publishing" | "published" | "unpublishing" | "unpublish_failed" | "unpublished";
        /** @enum {string} */
        BulletinVersionStatus: "draft" | "publishing" | "published" | "unpublishing" | "unpublish_failed" | "unpublished";
        /** @enum {string} */
        ContentModule: "news" | "history" | "videos";
        /** @enum {string} */
        ContentStatus: "draft" | "publishing" | "published" | "publish_failed" | "unpublishing" | "unpublish_failed" | "unpublished";
        PageMeta: {
            page: number;
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        ErrorBody: {
            code: string;
            message: string;
        };
        BulletinVersion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            issueId: string;
            locale: components["schemas"]["Locale"];
            title: string;
            subtitle: string;
            pdfAssetId: string;
            pdfFileName: string;
            publicGrantId?: string;
            status: components["schemas"]["BulletinVersionStatus"];
            workflowStatus?: string;
            workflowError?: string;
            /** Format: int64 */
            version: number;
            /** Format: date-time */
            publishedAt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        BulletinIssue: {
            /** Format: uuid */
            id: string;
            issueNumber?: number;
            /** Format: date */
            issueDate: string;
            status: components["schemas"]["BulletinStatus"];
            /** @enum {string} */
            notificationStatus: "not_requested" | "pending" | "queued" | "failed";
            /** Format: date-time */
            notificationQueuedAt?: string;
            /** @enum {string} */
            notificationErrorCode?: "NOTIFICATION_QUEUE_FAILED";
            /** Format: int64 */
            version: number;
            createdBy: string;
            updatedBy: string;
            /** Format: date-time */
            publishedAt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            versions: components["schemas"]["BulletinVersion"][];
        };
        BulletinRevision: {
            /** Format: int64 */
            version: number;
            snapshot: components["schemas"]["BulletinIssue"];
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
        };
        PublicBulletin: {
            /** Format: date */
            issueDate: string;
            issueNumber?: number;
            locale: components["schemas"]["Locale"];
            title: string;
            subtitle: string;
            downloadUrl: string;
            downloadFileName: string;
            /** Format: date-time */
            publishedAt: string;
            /** Format: int64 */
            version: number;
        };
        PublicBulletinIssue: {
            /** Format: date */
            issueDate: string;
            issueNumber?: number;
            versions: components["schemas"]["PublicBulletin"][];
        };
        Workflow: {
            /** Format: uuid */
            id: string;
            status: string;
            /** Format: int64 */
            aggregateVersion: number;
            /** Format: date-time */
            createdAt: string;
        };
        AssetSummary: {
            id: string;
        };
        UploadTarget: {
            /** Format: uri */
            url: string;
            method: string;
            headers: {
                [key: string]: string;
            };
            /** Format: date-time */
            expiresAt: string;
        };
        CreatedUpload: {
            asset: components["schemas"]["AssetSummary"];
            uploadTarget: components["schemas"]["UploadTarget"];
        };
        CreateBulletinInput: {
            issueNumber: number;
            /** Format: date */
            issueDate: string;
        };
        UpdateBulletinInput: {
            issueNumber: number;
            /** Format: date */
            issueDate: string;
        };
        CreateBulletinUploadInput: {
            locale: components["schemas"]["Locale"];
            fileName: string;
            /** @constant */
            mimeType: "application/pdf";
            /** Format: int64 */
            sizeBytes: number;
        };
        UpdateBulletinVersionInput: {
            title: string;
            subtitle: string;
        };
        CompleteBulletinUploadInput: {
            locale: components["schemas"]["Locale"];
            title: string;
            subtitle: string;
            fileName: string;
            /** @constant */
            mimeType: "application/pdf";
            /** Format: int64 */
            sizeBytes: number;
            checksumSha256: string;
        };
        CreateImageUploadInput: {
            /**
             * @default detail
             * @enum {string}
             */
            usage: "detail" | "home";
            fileName: string;
            /** @enum {string} */
            mimeType: "image/jpeg" | "image/png" | "image/webp";
            /** Format: int64 */
            sizeBytes: number;
        };
        CompleteImageUploadInput: {
            fileName: string;
            /** @enum {string} */
            mimeType: "image/jpeg" | "image/png" | "image/webp";
            /** Format: int64 */
            sizeBytes: number;
            checksumSha256: string;
        };
        AssetStatus: {
            id: string;
            /** @enum {string} */
            uploadStatus: "created" | "completed" | "failed";
            /** @enum {string} */
            scanStatus: "pending" | "clean" | "infected" | "failed";
            /** @enum {string} */
            processingStatus: "pending" | "ready" | "not_required" | "failed";
            retryable: boolean;
        };
        PublicationInput: {
            locale: components["schemas"]["Locale"];
            /**
             * @description Queue one Web Push campaign after the bulletin is publicly available. Ignored by unpublish operations.
             * @default false
             */
            notifySubscribers: boolean;
        };
        ContentTranslation: {
            locale: components["schemas"]["Locale"];
            title: string;
            summary?: string;
            body?: string;
            dateLabel?: string;
            imageAlt?: string;
        };
        ContentWriteInput: {
            slug?: string;
            /** Format: date */
            displayDate?: string;
            eventDate?: string;
            youtubeVideoId?: string;
            coverAssetId?: string;
            homeCoverAssetId?: string;
            /**
             * @default top
             * @enum {string}
             */
            detailLayout: "top" | "left" | "right";
            featured?: boolean;
            homeEligible?: boolean;
            translations: components["schemas"]["ContentTranslation"][];
            /** @description Locales omitted from translations are preserved unless they are named here for explicit deletion. */
            deleteLocales?: components["schemas"]["Locale"][];
        };
        ContentItem: components["schemas"]["ContentWriteInput"] & {
            /** Format: uuid */
            id: string;
            module: components["schemas"]["ContentModule"];
            status: components["schemas"]["ContentStatus"];
            /** Format: int64 */
            version: number;
            coverUrl?: string;
            homeCoverUrl?: string;
            isPublished: boolean;
            /** Format: int64 */
            publishedVersion?: number;
            createdBy: string;
            updatedBy: string;
            /** Format: date-time */
            publishedAt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ContentRevision: {
            /** Format: int64 */
            version: number;
            snapshot: components["schemas"]["ContentItem"];
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
        };
        PublicContentItem: {
            id: string;
            title: string;
            resolvedLocale: components["schemas"]["Locale"];
            availableLocales: components["schemas"]["Locale"][];
            summary?: string;
            body?: string;
            dateLabel?: string;
            /** Format: date */
            displayDate?: string;
            eventDate?: string;
            imageAlt?: string;
            imageUrl?: string;
            homeImageUrl?: string;
            href?: string;
            youtubeVideoId?: string;
            featured?: boolean;
            homeEligible?: boolean;
            /** @enum {string} */
            detailLayout?: "top" | "left" | "right";
        };
        BulletinIssueEnvelope: {
            data: components["schemas"]["BulletinIssue"];
            meta: {
                [key: string]: unknown;
            };
            error?: null;
        };
        BulletinListEnvelope: {
            data: components["schemas"]["BulletinIssue"][];
            meta: components["schemas"]["PageMeta"];
            error?: null;
        };
        BulletinRevisionListEnvelope: {
            data: components["schemas"]["BulletinRevision"][];
            meta: {
                [key: string]: unknown;
            };
            error?: null;
        };
        PublicBulletinEnvelope: {
            data: components["schemas"]["PublicBulletin"];
            meta: {
                [key: string]: unknown;
            };
            error?: null;
        };
        PublicBulletinListEnvelope: {
            data: components["schemas"]["PublicBulletinIssue"][];
            meta: components["schemas"]["PageMeta"];
            error?: null;
        };
        CreatedUploadEnvelope: {
            data: components["schemas"]["CreatedUpload"];
            meta: {
                [key: string]: unknown;
            };
            error?: null;
        };
        WorkflowEnvelope: {
            data: components["schemas"]["Workflow"];
            meta: {
                [key: string]: unknown;
            };
            error?: null;
        };
        ErrorEnvelope: {
            data: null;
            meta: {
                [key: string]: unknown;
            };
            error: components["schemas"]["ErrorBody"];
        };
        ContentItemEnvelope: {
            data: components["schemas"]["ContentItem"];
            meta: {
                [key: string]: unknown;
            };
            error?: null;
        };
        ContentListEnvelope: {
            data: components["schemas"]["ContentItem"][];
            meta: components["schemas"]["PageMeta"];
            error?: null;
        };
        ContentRevisionListEnvelope: {
            data: components["schemas"]["ContentRevision"][];
            meta: {
                [key: string]: unknown;
            };
            error?: null;
        };
        PublicContentListEnvelope: {
            data: components["schemas"]["PublicContentItem"][];
            meta: components["schemas"]["PageMeta"];
            error?: null;
        };
        PublicContentItemEnvelope: {
            data: components["schemas"]["PublicContentItem"];
            meta: {
                [key: string]: unknown;
            };
            error?: null;
        };
        HomeEnvelope: {
            data: {
                news: components["schemas"]["PublicContentItem"][];
                videos: components["schemas"]["PublicContentItem"][];
            };
            meta: {
                [key: string]: unknown;
            };
            error?: null;
        };
        AssetStatusEnvelope: {
            data: components["schemas"]["AssetStatus"];
            meta: {
                [key: string]: unknown;
            };
            error?: null;
        };
    };
    responses: {
        /** @description Bulletin issue */
        BulletinIssue: {
            headers: {
                ETag?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BulletinIssueEnvelope"];
            };
        };
        /** @description Published bulletin */
        PublicBulletin: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["PublicBulletinEnvelope"];
            };
        };
        /** @description Standard API error envelope */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Typed content item */
        ContentItem: {
            headers: {
                ETag?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ContentItemEnvelope"];
            };
        };
        /** @description Published localized content */
        PublicContentList: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["PublicContentListEnvelope"];
            };
        };
        /** @description Published localized content item */
        PublicContentItem: {
            headers: {
                ETag?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["PublicContentItemEnvelope"];
            };
        };
    };
    parameters: {
        Locale: components["schemas"]["Locale"];
        Page: number;
        PageSize: number;
        /** @description Searches the internal campaign name and localized subject or body. */
        SearchQuery: string;
        IssueID: string;
        IdempotencyKey: string;
        IfMatch: string;
        ContentModule: components["schemas"]["ContentModule"];
        ContentID: string;
        Revision: number;
    };
    requestBodies: {
        PublicationInput: {
            content: {
                "application/json": components["schemas"]["PublicationInput"];
            };
        };
        ContentWriteInput: {
            content: {
                "application/json": components["schemas"]["ContentWriteInput"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCampaigns: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
                /** @description Searches the internal campaign name and localized subject or body. */
                q?: components["parameters"]["SearchQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaign page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCampaign"];
            };
        };
        responses: {
            /** @description Campaign draft created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaign detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCampaign"];
            };
        };
        responses: {
            /** @description Campaign draft updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaign draft deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sendCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaign audience snapshotted and queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCampaignDeliveries: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                campaignId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaign delivery results and summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    retryFailedCampaignDeliveries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Failed deliveries queued for retry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCampaignSchedules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaign schedules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createCampaignSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCampaignSchedule"];
            };
        };
        responses: {
            /** @description Campaign schedule created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCampaignSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaign schedule detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCampaignSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCampaignSchedule"];
            };
        };
        responses: {
            /** @description Campaign schedule updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteCampaignSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaign schedule deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPublicBulletins: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published bulletin page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicBulletinListEnvelope"];
                };
            };
        };
    };
    getLatestPublicBulletin: {
        parameters: {
            query?: {
                locale?: components["parameters"]["Locale"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PublicBulletin"];
            404: components["responses"]["Error"];
        };
    };
    getPublicBulletinByNumber: {
        parameters: {
            query?: {
                locale?: components["parameters"]["Locale"];
            };
            header?: never;
            path: {
                issueNumber: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PublicBulletin"];
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getPublicBulletinByDate: {
        parameters: {
            query?: {
                locale?: components["parameters"]["Locale"];
            };
            header?: never;
            path: {
                issueDate: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PublicBulletin"];
            404: components["responses"]["Error"];
        };
    };
    listPublicNews: {
        parameters: {
            query?: {
                locale?: components["parameters"]["Locale"];
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PublicContentList"];
        };
    };
    getPublicNews: {
        parameters: {
            query?: {
                locale?: components["parameters"]["Locale"];
            };
            header?: {
                "If-None-Match"?: string;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PublicContentItem"];
            /** @description Content has not changed */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    listPublicHistory: {
        parameters: {
            query?: {
                locale?: components["parameters"]["Locale"];
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PublicContentList"];
        };
    };
    listPublicVideos: {
        parameters: {
            query?: {
                locale?: components["parameters"]["Locale"];
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PublicContentList"];
        };
    };
    getPublicHome: {
        parameters: {
            query?: {
                locale?: components["parameters"]["Locale"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published home page projection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeEnvelope"];
                };
            };
        };
    };
    listAdminBulletins: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
                status?: components["schemas"]["BulletinStatus"];
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CMS bulletin list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulletinListEnvelope"];
                };
            };
        };
    };
    createBulletinIssue: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBulletinInput"];
            };
        };
        responses: {
            201: components["responses"]["BulletinIssue"];
            409: components["responses"]["Error"];
        };
    };
    getAdminBulletin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: components["parameters"]["IssueID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BulletinIssue"];
            404: components["responses"]["Error"];
        };
    };
    updateBulletinIssue: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                issueId: components["parameters"]["IssueID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBulletinInput"];
            };
        };
        responses: {
            200: components["responses"]["BulletinIssue"];
            409: components["responses"]["Error"];
            412: components["responses"]["Error"];
        };
    };
    deleteBulletin: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                issueId: components["parameters"]["IssueID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bulletin and its revisions deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
            412: components["responses"]["Error"];
        };
    };
    createBulletinUploadSession: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                issueId: components["parameters"]["IssueID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBulletinUploadInput"];
            };
        };
        responses: {
            /** @description Short-lived asset upload target created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedUploadEnvelope"];
                };
            };
        };
    };
    updateBulletinVersion: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                issueId: components["parameters"]["IssueID"];
                locale: components["schemas"]["Locale"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBulletinVersionInput"];
            };
        };
        responses: {
            200: components["responses"]["BulletinIssue"];
            409: components["responses"]["Error"];
            412: components["responses"]["Error"];
        };
    };
    deleteBulletinVersion: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                issueId: components["parameters"]["IssueID"];
                locale: components["schemas"]["Locale"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BulletinIssue"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            412: components["responses"]["Error"];
        };
    };
    getBulletinAssetStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: components["parameters"]["IssueID"];
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bulletin PDF scan status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetStatusEnvelope"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    retryBulletinAssetScan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: components["parameters"]["IssueID"];
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bulletin PDF scan requeued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetStatusEnvelope"];
                };
            };
            409: components["responses"]["Error"];
        };
    };
    completeBulletinUpload: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                issueId: components["parameters"]["IssueID"];
                assetId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteBulletinUploadInput"];
            };
        };
        responses: {
            200: components["responses"]["BulletinIssue"];
            412: components["responses"]["Error"];
        };
    };
    publishBulletin: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                issueId: components["parameters"]["IssueID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["PublicationInput"];
        responses: {
            /** @description Publication workflow accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowEnvelope"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    unpublishBulletin: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                issueId: components["parameters"]["IssueID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["PublicationInput"];
        responses: {
            200: components["responses"]["BulletinIssue"];
            412: components["responses"]["Error"];
        };
    };
    listBulletinRevisions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: components["parameters"]["IssueID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bulletin revisions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulletinRevisionListEnvelope"];
                };
            };
        };
    };
    restoreBulletinRevision: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                issueId: components["parameters"]["IssueID"];
                revision: components["parameters"]["Revision"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BulletinIssue"];
            404: components["responses"]["Error"];
            412: components["responses"]["Error"];
        };
    };
    listAdminContent: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
                q?: string;
                status?: components["schemas"]["ContentStatus"];
                sort?: "updatedAt" | "displayDate" | "eventDate";
                direction?: "asc" | "desc";
            };
            header?: never;
            path: {
                module: components["parameters"]["ContentModule"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Typed content list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentListEnvelope"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    createContent: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                module: components["parameters"]["ContentModule"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ContentWriteInput"];
        responses: {
            201: components["responses"]["ContentItem"];
            409: components["responses"]["Error"];
        };
    };
    getAdminContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module: components["parameters"]["ContentModule"];
                contentId: components["parameters"]["ContentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ContentItem"];
            404: components["responses"]["Error"];
        };
    };
    updateContent: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                module: components["parameters"]["ContentModule"];
                contentId: components["parameters"]["ContentID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ContentWriteInput"];
        responses: {
            200: components["responses"]["ContentItem"];
            /** @description Existing locales omitted from `translations` must be listed in `deleteLocales` (error code `locale_set_mismatch`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            412: components["responses"]["Error"];
        };
    };
    deleteContent: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                module: components["parameters"]["ContentModule"];
                contentId: components["parameters"]["ContentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Content and its revisions deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
            412: components["responses"]["Error"];
        };
    };
    publishContent: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                module: components["parameters"]["ContentModule"];
                contentId: components["parameters"]["ContentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ContentItem"];
            422: components["responses"]["Error"];
        };
    };
    unpublishContent: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                module: components["parameters"]["ContentModule"];
                contentId: components["parameters"]["ContentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ContentItem"];
        };
    };
    listContentRevisions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module: components["parameters"]["ContentModule"];
                contentId: components["parameters"]["ContentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Content revisions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentRevisionListEnvelope"];
                };
            };
        };
    };
    restoreContentRevision: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                module: components["parameters"]["ContentModule"];
                contentId: components["parameters"]["ContentID"];
                revision: components["parameters"]["Revision"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ContentItem"];
        };
    };
    createNewsCoverUpload: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                contentId: components["parameters"]["ContentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateImageUploadInput"];
            };
        };
        responses: {
            /** @description News cover upload target */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedUploadEnvelope"];
                };
            };
        };
    };
    getNewsCoverStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contentId: components["parameters"]["ContentID"];
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description News cover scan and processing status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetStatusEnvelope"];
                };
            };
        };
    };
    retryNewsCoverScan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contentId: string;
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description News cover scan requeued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetStatusEnvelope"];
                };
            };
            409: components["responses"]["Error"];
        };
    };
    completeNewsCoverUpload: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                contentId: components["parameters"]["ContentID"];
                assetId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteImageUploadInput"];
            };
        };
        responses: {
            200: components["responses"]["ContentItem"];
        };
    };
}
